# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoKitExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DemoKitExtension
  pod 'UIKitExtension', :path => '../'

  target 'DemoKitExtensionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoKitExtensionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
